---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nhash_behaviour=merge' >> ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # First run, check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo --check -vvvv

  # First run, actual
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo -vvvv

  # Idempotency test
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - sudo stat /etc/ircd-hybrid/ircd.conf
  - sudo stat /etc/ircd-hybrid/ircd.motd

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
