---
- name: Install ircd-hybrid
  apt:
    name:   ircd-hybrid
    state:  present

- name: Copy across IRCD configuration
  template:
    src:  ircd.conf.j2
    dest: /etc/ircd-hybrid/ircd.conf
  notify:
  - restart ircd

- name: Copy across IRCD MOTD
  template:
    src:  ircd.motd.j2
    dest: /etc/ircd-hybrid/ircd.motd
  notify:
  - restart ircd
