---
- name: Install ircd-hybrid
  apt:
    name:   ircd-hybrid
    state:  present
    update_cache: yes
  become: yes
  
- name:   Reload available services
  shell:  initctl reload-configuration
  when:   ansible_distribution == 'Ubuntu'

- name: Copy across IRCD configuration
  template:
    src:  ircd.conf.j2
    dest: /etc/ircd-hybrid/ircd.conf
  become: yes
  notify:
    - Restart ircd

- name: Copy across IRCD MOTD
  template:
    src:  ircd.motd.j2
    dest: /etc/ircd-hybrid/ircd.motd
  become: yes
  notify:
    - Restart ircd
